language: php

php:
  - 7.2
  - 7.4

services:
  - postgresql
  - mysql

env:
  global:
    - DEFAULT=1
  matrix:
    - DB=mysql DB_DSN='mysql://root@127.0.0.1/cakephp_test?init[]=SET sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"'
    - DB=pgsql DB_DSN='postgres://postgres@127.0.0.1/cakephp_test'
    - DB=sqlite DB_DSN='sqlite:///:memory:'

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: PHPCS=1 DEFAULT=0

    - php: 7.2
      env: STATIC_ANALYSIS=1 DEFAULT=0

    - php: 7.2
      env: PREFER_LOWEST=1 DEFAULT=0

before_install:
  - if [[ $DB == 'mysql' ]]; then mysql -u root -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

install:
  - if [[ $DB != 'mysql' && $TRAVIS_PHP_VERSION != 7.4 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $STATIC_ANALYSIS != 1 ]]; then composer install --no-interaction; fi
  - |
      if [[ $STATIC_ANALYSIS == 1 ]]; then
        composer require phpstan/phpstan:^0.12
        composer require psalm/phar:^3.7
        composer install --no-dev
      fi

script:
  - if [[ $DB == 'mysql' && $TRAVIS_PHP_VERSION == 7.4 ]]; then ./vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $DEFAULT == 1 ]]; then ./vendor/bin/phpunit; fi

  - if [[ $PHPCS == 1 ]]; then ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

  - if [[ $STATIC_ANALYSIS == 1 ]]; then vendor/bin/phpstan analyse src; fi
  - if [[ $STATIC_ANALYSIS == 1 ]]; then vendor/bin/psalm.phar; fi

after_success:
- if [[ $DB == 'mysql' && $TRAVIS_PHP_VERSION == 7.4 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
