language: php

php:
  - 7.2
  - 7.3
  - 7.4

dist: xenial

env:
  global:
    - DEFAULT=1
    - CODECOVERAGE=0

services:
  - mysql
  - postgresql

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: CODECOVERAGE=1 DEFAULT=0

    - php: 7.2
      env: PHPCS=1 DEFAULT=0

    - php: 7.2
      env: STATIC_ANALYSIS=1 DEFAULT=0

    - php: 7.2
      env: PREFER_LOWEST=1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.2 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $STATIC_ANALYSIS = 1 ]]; then composer require --dev phpstan/phpstan:^0.12 psalm/phar:^3.7; fi
  - if [[ $STATIC_ANALYSIS != 1 ]]; then composer install --no-interaction; fi

script:
  - if [[ $CODECOVERAGE = 1 ]]; then ./vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $DEFAULT = 1 ]]; then ./vendor/bin/phpunit; fi

  - if [[ $PHPCS = 1 ]]; then ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

  - if [[ $STATIC_ANALYSIS = 1 ]]; then vendor/bin/phpstan.phar analyse src; fi
  - if [[ $STATIC_ANALYSIS = 1 ]]; then vendor/bin/psalm.phar analyse src; fi

after_success:
- if [[ $CODECOVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
